### ISSUE TITLE
Warning: Functions are not valid as a React child.

### ISSUE THREAD

**Issue by Anonymous7code** [creativetimofficial/vision-ui-dashboard-react#5]
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    at Routes (http://localhost:3000/static/js/bundle.js:414109:5)
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:56183:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:55885:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:56203:5)
    at App (http://localhost:3000/static/js/bundle.js:716:97)
    at VisionUIControllerProvider (http://localhost:3000/static/js/bundle.js:9684:5)
    at Router (http://localhost:3000/static/js/bundle.js:414042:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:412851:5)
printWarning @ react-dom.development.js:86

**Comment by simmmpleweb** [comment]
Hello, @Anonymous7code ! Thanks for using our products. It will be helpful for us to use the issue template so we can understand your problem better. Regards, Vlad.
